### ISSUE TITLE
No module named pyaudio

### ISSUE THREAD

**Issue by pine3825** [bwhitman/respeaker-xmos-hid#2]
Dear
On Linux, I tried that.
but there is any problems as below.
How can I resolve??
=========================================
python listen_and_get_position.py
Traceback (most recent call last):
  File "listen_and_get_position.py", line 1, in <module>
    import wave, os, pyaudio, time
ImportError: No module named pyaudio

==> I resolved above problems by sudo apt-get install python-pyaudio
But, There is another problem.

    import hid # https://pypi.python.org/pypi/hidapi aka https://github.com/trezor/cython-hidapi
ImportError: No module named hid

**Comment by pine3825** [comment]
Dear 
Could you have any idea?
------------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/respeaker-xmos-hid$ ls
hidapi                      main.c    node_modules  registers.csv
listen_and_get_position.py  Makefile  README.md
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/respeaker-xmos-hid$ python listen_and_get_position.py 
Traceback (most recent call last):
  File "listen_and_get_position.py", line 2, in <module>
    import hid # https://pypi.python.org/pypi/hidapi aka https://github.com/trezor/cython-hidapi
ImportError: No module named hid
==================================================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/respeaker-xmos-hid$ make
gcc -o respeaker_hid main.o -L/usr/local/lib -lhidapi
/usr/bin/ld: cannot find -lhidapi
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'respeaker_hid' failed
make: *** [respeaker_hid] Error 1

**Comment by pine3825** [comment]
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/respeaker-xmos-hid$ python listen_and_get_position.py 
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings

**Comment by pine3825** [comment]
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/respeaker-xmos-hid$ python listen_and_get_position.py 
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
